environment:
  nodejs_version: "6"

services:
  - mongodb
  
before_test:
  - cmd: set PATH=%NODE_ENV%;test
  - cmd: set PATH="%PATH%;C:\Program Files\nodejs"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test


build: off
